### ISSUE TITLE
React.VFC is marked deprecated

### ISSUE THREAD

**Issue by Steven-Chan** [oursky/eslint-oursky#39]
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/8ce24999967467fd6cae8639fde57697a13212a9

**Comment by louischan-oursky** [comment]
Yes, it is deprecated in version 18. However, major frameworks are not React 18 ready. People are still using React 17. The type definition of non-VFC types is problematic because [it unconditionally allow `children` prop even the component does not support it.](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/55dc209ceb6dbcd59c4c68cc8dfb77faadd9de12#diff-32cfd8cb197872bcba371f5018185d2e75fa540b52cda2dd7d8ac12dcc021299R511)

**Comment by louischan-oursky** [comment]
That rule was removed in 15.0.0
